# Generated by Django 3.1.4 on 2020-12-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, null=True, unique=True, verbose_name='Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, null=True, unique=True, verbose_name='Turma')),
                ('disciplinas', models.ManyToManyField(related_name='turmas', to='alunos.Disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, null=True, verbose_name='Nacionalidade')),
                ('pais', models.CharField(max_length=100, null=True, verbose_name='País')),
                ('sigla', models.CharField(max_length=2, null=True)),
            ],
            options={
                'unique_together': {('nome', 'pais', 'sigla')},
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10, null=True, unique=True, verbose_name='Nome')),
                ('nome', models.CharField(max_length=150, null=True, verbose_name='Nome')),
                ('Nacionalidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='alunos.nacionalidade')),
            ],
        ),
    ]
