# Generated by Django 3.1.4 on 2020-12-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_auto_20201217_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='Nacionalidade',
            new_name='nacionalidade',
        ),
    ]
