# Generated by Django 3.1.4 on 2020-12-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_auto_20201217_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='nacionalidade',
            new_name='Nacionalidade',
        ),
    ]
